
services:
  sharpconsole.simple:
    extends:
      file: docker/simple/docker-compose.simple.yml
      service: run

  sharpconsole.entity-inmemory:
    extends:
      file: docker/entity-inmemory/docker-compose.entity-inmemory.yml
      service: run


