
services:
  sharpconsole.simple:
    extends:
      file: docker/simple/docker-compose.simple.yml
      service: run

  sharpconsole.entity-in-memory:
    extends:
      file: docker/entity-in-memory/docker-compose.entity-in-memory.yml
      service: run


