services:
  sharpconsole.simple:
    extends:
      file: docker/simple/docker-compose.simple.yml
      service: run

  sharpconsole.entity-in-memory:
    extends:
      file: docker/entity-in-memory/docker-compose.entity-in-memory.yml
      service: run

  sharpconsole.entity-with-database:
    extends:
      file: docker/entity-with-database/docker-compose.entity-with-database.yml
      service: run
    networks:
      - sharpconsole-entity-with-database-network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    extends:
      file: docker/database/docker-compose.database.yml
      service: postgres
    networks:
      - sharpconsole-entity-with-database-network

networks:
  sharpconsole-entity-with-database-network:
    driver: bridge
